# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  fr: Julien Duroure
  en: Julien Duroure
email: contact@julienduroure.com
description:
  fr: Rigging - Animation - Formation - DÃ©veloppement
  en: Rigging - Animation - Training - Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://julienduroure.com" # the base hostname & protocol for your site

index:
  en: /
  fr: /fr/

twitter_username: julienduroure
github_username:  julienduroure
analytics: UA-35258207-1 #false or UA_ID

copyright: "&copy 2016-2019 Julien Duroure"

# Build settings
markdown: kramdown

exclude: [Gemfile, Gemfile.lock, TODO.txt, _template/, _dev.yml, import_external.py, README.md]

collections:
  blerifa:
    output: false
  prez:
    output: true
  old_prez:
    output: false
  ready:
    output: true
  customer:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      assets: ""

  -
    scope:
      path: ""
      type: "prez"
    values:
      assets: ""

  -
    scope:
      path: ""
      type: "old_prez"
    values:
      assets: ""

plugins:
  - jekyll-redirect-from
